app:
  environment: "development"
  host: "localhost:12000"
  protocol: "http"

server:
  port: "8080"
  workers: 5

postgresql_host: "postgres://postgres:postgres@db:5432/postgres?sslmode=disable"

rabbitmq_host: "rabbitmq"
rabbitmq_port: 5672
rabbitmq_user: "guest"
rabbitmq_pass: "guest"
rabbitmq_kind: "topic"

minio:
  url: "minio:9000"
  access_id: "minioadmin"
  secret_access_key: "minioadmin"
  bucket: "edtech-content"